package com.hmisdoctor.ui.emr_workflow.prescription.model

data class PrescriptionDetail(
    var administer_detail_status_uuid: Int? = 0,
    var administred_quantity: Int? = 0,
    var comments: String? = "",
    var created_by: Int? = 0,
    var created_date: String? = "",
    var dispense_detail_status_uuid: Int? = 0,
    var dispensed_quantity: Int? = 0,
    var drug_frequency: DrugFrequency? = DrugFrequency(),
    var drug_frequency_uuid: Int? = 0,
    var drug_instruction: DrugInstruction? = DrugInstruction(),
    var drug_instruction_uuid: Int? = 0,
    var drug_route: DrugRoute? = DrugRoute(),
    var drug_route_uuid: Int? = 0,
    var duration: Int? = 0,
    var duration_period: DurationPeriod? = DurationPeriod(),
    var duration_period_uuid: Int? = 0,
    var generic_uuid: Int? = 0,
    var is_active: Boolean? = false,
    var is_added_to_treatment_plan: Boolean? = false,
    var is_emar: Boolean? = false,
    var is_reusable: IsReusable? = IsReusable(),
    var item_master: ItemMaster? = ItemMaster(),
    var item_master_uuid: Int? = 0,
    var modified_by: Int? = 0,
    var modified_date: String? = "",
    var prescribed_quantity: Int? = 0,
    var prescription_uuid: Int? = 0,
    var revision: Int? = 0,
    var status: Boolean? = false,
    var tat_end_time: Any? = Any(),
    var tat_start_time: Any? = Any(),
    var treatment_plan_drug_map_uuid: Int? = 0,
    var uuid: Int? = 0
)