package com.hmisdoctor.ui.emr_workflow.prescription.model

data class PrescriptionResult(
    var administer_status_uuid: Int? = 0,
    var appointment_uuid: Int? = 0,
    var comments: Any? = Any(),
    var consultation_uuid: Int? = 0,
    var created_by: String? = "",
    var created_date: String? = "",
    var department_uuid: String? = "",
    var diagnosis_uuid: Int? = 0,
    var dispense_status_uuid: Int? = 0,
    var dispensed_by: Int? = 0,
    var doctor_uuid: String? = "",
    var encounter_type_uuid: Int? = 0,
    var encounter_uuid: Int? = 0,
    var facility_uuid: String? = "",
    var has_e_mar: Boolean? = false,
    var injection_room_uuid: Int? = 0,
    var is_active: Boolean? = false,
    var is_discharge_medication: Boolean? = false,
    var modified_by: String? = "",
    var modified_date: String? = "",
    var notes: String? = "",
    var other_diagnosis: Any? = Any(),
    var patient_treatment_uuid: Int? = 0,
    var patient_uuid: String? = "",
    var prescription_date: String? = "",
    var prescription_no: String? = "",
    var prescription_status_uuid: Int? = 0,
    var revision: Int? = 0,
    var status: Boolean? = false,
    var store_master_uuid: Int? = 0,
    var treatment_kit_uuid: Int? = 0,
    var uuid: Int? = 0,
    var ward_master_uuid: Int? = 0
)