package com.hmisdoctor.ui.emr_workflow.diagnosis.model

data class DiagonosisResponseContent(
    var body_site_uuid: Int? = 0,
    var category_uuid: Int? = 0,
    var comments: String? = "",
    var condition_status_uuid: Int? = 0,
    var condition_type_uuid: Int? = 0,
    var consultation_uuid: Int? = 0,
    var created_by: String? = "",
    var created_date: String? = "",
    var department_uuid: String? = "",
    var diagnosis_uuid: String? = "",
    var encounter_type_uuid: EncounterTypeUuid = EncounterTypeUuid(),
    var encounter_uuid: Int? = 0,
    var facility_uuid: String? = "",
    var grade_uuid: Int? = 0,
    var is_active: Int? = 0,
    var is_chronic: Int? = 0,
    var is_patient_condition: Int? = 0,
    var is_snomed: Int? = 0,
    var modified_by: String? = "",
    var modified_date: String? = "",
    var other_diagnosis: String? = "",
    var patient_treatment_uuid: Int? = 0,
    var patient_uuid: String? = "",
    var performed_by: String? = "",
    var prescription_uuid: Int? = 0,
    var revision: Int? = 0,
    var status: Int? = 0,
    var tat_end_time: String? = "",
    var tat_start_time: String? = "",
    var test_master_type_uuid: Int? = 0,
    var type_uuid: Int? = 0,
    var user_uuid: String? = "",
    var uuid: Int? = 0
)