package com.hmisdoctor.ui.quick_reg.model

data class FacilityLocation(
    var address_line1: String = "",
    var address_line2: String = "",
    var area_uuid: String = "",
    var block_master: String = "",
    var block_uuid: Int = 0,
    var city_uuid: Int = 0,
    var corporation_master: Any = Any(),
    var corporation_uuid: Int = 0,
    var country_master: CountryMaster = CountryMaster(),
    var country_uuid: Int = 0,
    var created_by: Int = 0,
    var created_date: Any = Any(),
    var district_master: DistrictMaster = DistrictMaster(),
    var district_uuid: Int = 0,
    var facility: Facility = Facility(),
    var facility_uuid: Int = 0,
    var hud_master: Any = Any(),
    var hud_uuid: Int = 0,
    var is_active: Boolean = false,
    var landline: String = "",
    var latitude: String = "",
    var location_type_uuid: Any = Any(),
    var longitude: String = "",
    var modified_by: Int = 0,
    var modified_date: String = "",
    var muncipality_master: Any = Any(),
    var municipality_uuid: Int = 0,
    var pincode_uuid: Int = 0,
    var revenue_division_uuid: Any = Any(),
    var revision: Int = 0,
    var state_master: StateMaster = StateMaster(),
    var state_uuid: Int = 0,
    var status: Boolean = false,
    var sub_district_master: Any = Any(),
    var sub_district_uuid: Any = Any(),
    var taluk_master: Any = Any(),
    var taluk_uuid: Int = 0,
    var town_panchayat_uuid: Any = Any(),
    var uuid: Int = 0,
    var village_master: Any = Any(),
    var village_uuid: Int = 0
)