package com.hmisdoctor.ui.quick_reg.model

data class QuickRegistrationSaveresponseContent(
    val age: Int? = 0,
    val application_type_uuid: Int? = 0,
    val blood_group_uuid: Int? = 0,
    val created_by: String? = "",
    val created_date: String? = "",
    val dob: String? = "",
    //val fingerPrintData: FingerPrintData? = FingerPrintData(),
    val first_name: String? = "",
    val gender_uuid: Int? = 0,
    val is_active: Boolean? = false,
    val is_adult: Boolean? = false,
    val is_dob_auto_calculate: Boolean? = false,
    val last_name: String? = "",
    val middle_name: String? = "",
    val modified_by: String? = "",
    val modified_date: String? = "",
    val old_pin: String = "",
    val para_1: Any? = Any(),
  //  val patient_details: PatientDetails? = PatientDetails(),
    val patient_type_uuid: Int? = 0,
  //  val patient_visits: PatientVisits? = PatientVisits(),
   // val patients: Patients? = Patients(),
    val period_uuid: Int? = 0,
    val professional_title_uuid: Int? = 0,
    val registered_date: String? = "",
    val registred_facility_uuid: String? = "",
 //   val revision: Boolean? = false,
    val suffix_uuid: Int? = 0,
    val title_uuid: Int? = 0,
    val uhid: String? = "",
    val uuid: Int? = 0
//    val validatedData: ValidatedData? = ValidatedData()
)