package com.hmisdoctor.ui.quick_reg.model

data class SampleAcceptanceresponseContent(
    val analyte_master_uuid: Any? = Any(),
    val analyte_ref_master_uuid: Any? = Any(),
    val analyte_uom_uuid: Int? = 0,
    val created_date: String? = "",
    val doctor_uuid: Int? = 0,
    val encounter_uuid: Int? = 0,
    val facility_uuid: String? = "",
    val from_department_uuid: Int? = 0,
    val from_facility_uuid: String? = "",
    val from_to_location_uuid: Int? = 0,
    val group_uuid: Int? = 0,
    val is_active: Boolean? = false,
    val is_profile: Boolean? = false,
    val is_visible_from_facility: Boolean? = false,
    val is_visible_to_facility: Boolean? = false,
    val lab_master_type_uuid: Int? = 0,
    val modified_by: Int? = 0,
    val modified_date: String? = "",
    val order_priority_uuid: Int? = 0,
    val order_process_date: String? = "",
    val patient_order_detail_uuid: Int? = 0,
    val patient_order_test_detail_uuid: Int? = 0,
    val patient_order_uuid: Int? = 0,
    val patient_uuid: Int? = 0,
    val patient_work_order_uuid: Int? = 0,
    val profile_master_uuid: Any? = Any(),
    val sample_collection_by: String? = "",
    val sample_collection_date: String? = "",
    val sample_identifier: Int? = 0,
    val status: Boolean? = false,
    val test_master_uuid: Int? = 0,
    val test_to_location_uuid: Int? = 0,
    val to_department_uuid: Int? = 0,
    val to_sub_department_uuid: Int? = 0,
    val uuid: Int? = 0,
    val vendor_sample_uuid: Int? = 0,
    val vendor_test_uuid: Int? = 0,
    val work_order_status_uuid: Int? = 0
)