package com.hmisdoctor.ui.quick_reg.model

data class SaveOrder(
    var auth_status_uuid: Any = Any(),
    var cancel_reason_comment: Any = Any(),
    var cancel_reason_uuid: Any = Any(),
    var cancelled_by: Any = Any(),
    var cancelled_date_time: Any = Any(),
    var consultation_uuid: Int = 0,
    var created_by: Int = 0,
    var created_date: String = "",
    var department_uuid: Int = 0,
    var doctor_uuid: Int = 0,
    var encounter_doctor_uuid: Int = 0,
    var encounter_type_uuid: Int = 0,
    var encounter_uuid: Int = 0,
    var facility_uuid: Int = 0,
    var from_facility_name: Any = Any(),
    var is_active: Boolean = false,
    var is_direct_bill: Any = Any(),
    var is_visible_from_facility: Boolean = false,
    var is_visible_to_facility: Boolean = false,
    var lab_master_type_uuid: Int = 0,
    var modified_by: Int = 0,
    var modified_date: String = "",
    var order_completed_date: Any = Any(),
    var order_number: Int = 0,
    var order_request_date: String = "",
    var order_schedule_date: Any = Any(),
    var order_status_uuid: Int = 0,
    var order_to_location_uuid: Int = 0,
    var package_uuid: Any = Any(),
    var patient_treatment_uuid: Int = 0,
    var patient_uuid: Int = 0,
    var revision: Int = 0,
    var status: Boolean = false,
    var sub_department_uuid: Int = 0,
    var tat_session_end: String = "",
    var tat_session_start: String = "",
    var uuid: Int = 0,
    var ward_uuid: Any = Any()
)