package com.hmisdoctor.ui.covid.addpatientrequest

data class CovidPatientDetails(
    var address_line_1: String? = "",
    var address_line_2: String? = "",
    var atypical_presentation: Boolean? = false,
    var contact_type_uuid: Int? = 2,
    var country_uuid: Int? = 0,
    var diagnosis: String? = "",
    var differential_diagnosis: String? = "",
    var district_uuid: Int? = 0,
    var etiology_identified: String? = "",
    var facility_name: String? = "",
    var facility_pincode: String? = "",
    var first_symptom: String? = "",
    var health_care_worker: Boolean? = false,
    var hospital_name_address: String? = "",
    var hospital_phone_number: String? = "",
    var hospitialized_date: String? = "",
    var immunocompromosed_condition: Boolean? = false,
    var institution_name: String? ="",
    var other_nationality: String? = "",
    var other_underlying_conditions: String? = "",
    var passport_number: String = "",
    var patient_category_uuid: Int? = 0,
    var pincode: String? = "",
    var same_address: Boolean? = false,
    var state_uuid: Int? = 0,
    var taluk_uuid: Int? = 0,
    var test_request_type_uuid: Int? = 0,
    var test_result_uuid: Int? = 0,
    var unusual_unexpected_course: Boolean? = false,
    var village_uuid: Int? = 0
)